name: main

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  windows:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ocaml-compiler:
          - ocaml-base-compiler.5.1.0~beta1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          opam-pin: false
          opam-depext: false
          ocaml-compiler: ${{ matrix.ocaml-compiler }}


      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
